stateDiagram-v2
    direction LR
    [*] --> q0
    q0 --> q1 : (a,.) / (a,a) / (R,R)
    q1 --> q1 : (a,.) / (a,a) / (R,R)
    q1 --> q2 : (b,.) / (b,.) / (S,L)
    q2 --> q2 : (b,a) / (b,a) / (R,L)
    q2 --> q2 : (b,.) / (b,.) / (R,S)
    q2 --> q3 : (.,.) / (.,.) / (S,S)
    q3 --> [*]
